trigger:
  - main  # or any branch you want to trigger the pipeline

pool:
  name: 'Azure Pipelines'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'  # Ensure you have the right Python version
      architecture: 'x86'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pandas openpyxl
    displayName: 'Install Dependencies'

  - script: |
      python generate_dummy_report.py
    displayName: 'Generate Dummy Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dummy_report.xlsx'
      artifactName: 'DummyReport'
    displayName: 'Publish Excel Report'

  - script: |
      ls -la "$(Build.ArtifactStagingDirectory)/DummyReport/dummy_report.xlsx"
    displayName: 'Check Report File Path'

  - script: |
      chmod +r "$(Build.ArtifactStagingDirectory)/DummyReport/dummy_report.xlsx"
    displayName: 'Ensure File Permissions'

  - script: |
      BOT_TOKEN="7427451676:AAHRuoRuj8Wgr_zUUqFIsVmHvuXPmUbzNPM"
      CHAT_ID="5370229480"  # Replace with your chat ID
      REPORT_FILE="$(Build.ArtifactStagingDirectory)/DummyReport/dummy_report.xlsx"
      if [ -f "$REPORT_FILE" ]; then
        curl -v -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendDocument" \
             -F chat_id=$CHAT_ID \
             -F document=@"$REPORT_FILE" \
             -F caption="Dummy KPI Report has been generated and is attached."
      else
        echo "File not found: $REPORT_FILE"
      fi
    displayName: 'Send Report to Telegram'
