trigger:
  - main  # or any branch you want to trigger the pipeline

pool:
<<<<<<< HEAD
  name : 'Azure Pipelines'
=======
  vmImage: 'ubuntu-latest'
>>>>>>> 422d1b2584aae21d67e709ece6e10450ef472419

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'  # Ensure you have the right Python version
<<<<<<< HEAD
      architecture: 'x64'
=======
      architecture: 'x86'
>>>>>>> 422d1b2584aae21d67e709ece6e10450ef472419
      addToPath: true
    displayName: 'Use Python 3.12'

  - script: |
      python -m pip install --upgrade pip
      pip install pandas openpyxl
    displayName: 'Install Dependencies'

  - script: |
      python generate_dummy_report.py
    displayName: 'Generate Dummy Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dummy_report.xlsx'
      artifactName: 'DummyReport'
    displayName: 'Publish Excel Report'

  - script: |
      BOT_TOKEN="7427451676:AAHRuoRuj8Wgr_zUUqFIsVmHvuXPmUbzNPM"
      CHAT_ID="5370229480"  # Replace with your chat ID
      REPORT_URL="$(Build.ArtifactStagingDirectory)/DummyReport/dummy_report.xlsx"
      MESSAGE="Dummy KPI Report has been generated and is available at: $REPORT_URL"
      curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id=$CHAT_ID -d text="$MESSAGE"
    displayName: 'Send Report to Telegram'
