trigger:
  - main  # or any branch you want to trigger the pipeline

pool:
  name : 'Azure Pipelines'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'  # Ensure you have the right Python version
      architecture: 'x64'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pandas openpyxl
    displayName: 'Install Dependencies'

  - script: |
      python generate_dummy_report.py
    displayName: 'Generate Dummy Report'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'dummy_report.xlsx'
      artifactName: 'DummyReport'
    displayName: 'Publish Excel Report'

  - script: |
      BOT_TOKEN="7427451676:AAHRuoRuj8Wgr_zUUqFIsVmHvuXPmUbzNPM"
      CHAT_ID="5370229480"  # Replace with your chat ID
      REPORT_URL="$(Build.ArtifactStagingDirectory)/DummyReport/dummy_report.xlsx"
      MESSAGE="Dummy KPI Report has been generated and is available at: $REPORT_URL"
      curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" -d chat_id=$CHAT_ID -d text="$MESSAGE"
    displayName: 'Send Report to Telegram'
